import turtle as tur

def setup_canvas():
    """Sets up the turtle canvas and initial settings."""
    tur.speed(6)
    tur.bgcolor("black")
    tur.hideturtle()

def draw_first_curves():
    """Draws the initial curves of the figure."""
    tur.color("gold")
    tur.pensize(5)
    tur.left(60)
    tur.fd(50)
    tur.left(15)
    tur.circle(100, 90)
    tur.fd(30)
    tur.pensize(10)
    tur.penup()
    tur.right(90)
    tur.fd(20)
    tur.pendown()
    tur.right(40)
    tur.circle(-50, 90)
    tur.fd(20)
    tur.left(150)

def draw_head_curves():
    """Draws the second and third head curves."""
    # Second head curve
    tur.color("red")
    tur.penup()
    tur.fd(40)
    tur.left(20)
    tur.pendown()
    tur.circle(50, 90)

    # Third head curve (goes to beginning)
    tur.color("gold")
    tur.penup()
    tur.goto(0, 0)
    tur.pensize(5)
    tur.pendown()
    tur.left(30)
    tur.fd(120)
    tur.circle(60, 270)

def draw_eyes_and_brows():
    """Draws the eyes and eyebrows."""
    # Eyes
    tur.color("gold")
    tur.penup()
    tur.forward(30)
    tur.right(50)
    tur.forward(135)
    tur.pendown()
    tur.pensize(8)
    tur.circle(50, 90)
    tur.left(95)
    tur.penup()
    tur.circle(60, 75)

    # Eyebrows
    tur.penup()
    tur.forward(15)
    tur.left(90)
    tur.pensize(2)
    tur.pendown()
    tur.circle(70, 90)

def draw_ears():
    """Draws the ears."""
    tur.pensize(5)
    tur.penup()
    tur.forward(75)
    tur.right(90)
    tur.forward(20)
    tur.pendown()
    tur.circle(90, 90)
    tur.forward(20)
    tur.circle(30, 170)
    tur.right(180)
    tur.circle(28, 180)
    tur.right(160)
    tur.circle(25, 180)
    tur.right(160)
    tur.circle(22, 160)
    tur.forward(20)
    tur.circle(60, 45)

def draw_trunk():
    """Draws the trunk."""
    tur.penup()
    tur.goto(0, 0)
    tur.left(130)
    tur.fd(140)
    tur.right(250)
    tur.backward(20)
    tur.circle(80, 20)
    tur.circle(20, 40)
    tur.right(110)
    tur.penup()
    tur.fd(20)
    tur.pendown()
    tur.pensize(10)
    tur.forward(50)
    tur.circle(100, 80)
    tur.pensize(9)
    tur.circle(150, 50)
    tur.pensize(7)
    tur.circle(100, 60)
    tur.pensize(5)
    tur.circle(90, 60)
    tur.pensize(4)
    tur.circle(40, 60)
    tur.circle(10, 90)

def draw_head_details():
    """Draws details on the head."""
    tur.color("red")
    tur.penup()
    tur.goto(-90, 290)
    tur.right(230)
    tur.pendown()
    tur.circle(-100, 50)
    tur.circle(200, 20)
    tur.circle(50, 30)
    tur.right(180)
    tur.circle(50, 30)
    tur.circle(200, 20)
    tur.circle(-100, 40)
    tur.right(95)
    tur.penup()
    tur.fd(40)
    tur.right(90)
    tur.pendown()
    tur.circle(100, 40)
    tur.penup()
    tur.circle(35, 120)
    tur.right(30)
    tur.pendown()
    tur.pensize(5)
    tur.circle(60, 50)

def draw_tilak():
    """Draws the tilak (forehead mark)."""
    tur.penup()
    tur.goto(-70, 90)
    tur.fillcolor("red")
    tur.begin_fill()
    tur.circle(20, 180)
    tur.end_fill()
    tur.penup()
    tur.left(75)
    tur.fillcolor("red")
    tur.begin_fill()
    tur.circle(70, 35)
    tur.end_fill()
    tur.left(180)
    tur.backward(10)
    tur.pendown()
    tur.left(6)
    tur.pensize(5)
    tur.color("red")
    tur.circle(-80, 40)
    tur.penup()
    tur.goto(0, 0)

def write_text_and_border():
    """Writes the greeting and draws a border."""
    tur.color("deep sky blue")
    tur.penup()
    tur.setposition(-250, -300)
    tur.write("Happy\nGanesh\nChaturthi", font=("arial", 20, "normal"), align="left")
    tur.goto(-240, 420)
    tur.right(90)
    tur.forward(275)
    tur.right(130)
    tur.forward(100)
    tur.goto(0, 420)
    tur.right(90)
    tur.fd(100)
    tur.right(50)
    tur.pendown()
    tur.fd(510)
    tur.left(90)
    tur.right(165)
    tur.fd(540)
    tur.right(70)
    tur.fd(20)
    tur.fd(540)
    tur.right(90)
    tur.fd(20)
    tur.left(30)
    tur.fd(205)
    tur.right(90)
    tur.fd(20)
    # The tur.end_fill() from the original code was here, but it caused an error.

def draw_final_curve():
    """Draws the final decorative curve."""
    tur.color("red")
    tur.penup()
    tur.goto(0, 0)
    tur.left(118)
    tur.fd(240)
    tur.right(30)
    tur.pendown()
    tur.circle(90, 65)
    tur.penup()

def main():
    """Main function to run the drawing sequence."""
    setup_canvas()
    draw_first_curves()
    draw_head_curves()
    draw_eyes_and_brows()
    draw_ears()
    draw_trunk()
    draw_head_details()
    draw_tilak()
    write_text_and_border()
    draw_final_curve()
    tur.done()

if __name__ == "__main__":
    main()
